wandb_version: 1

batch_size:
  desc: null
  value: 64
seq_length:
  desc: null
  value: 32
hidden_size:
  desc: null
  value: 128
temperature:
  desc: null
  value: 2.0
_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730484699.236918
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.15
      5: 0.15.3
      8:
      - 5
